[package]
name = "msx_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.2"
clap = { version = "4.1.13", features = ["derive", "env"] }
env_logger = "0.10.0"
log = "0.4.17"
sdl2 = "0.35.2"
